'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace AcreditPrueba

    Partial Public Class Persona
        Public Property IdPersona As Integer
        Public Property Nombre As String
        Public Property Apellido As String
        Public Property Documento As String
    
        Public Overridable Property Venta As ICollection(Of Venta) = New HashSet(Of Venta)
    
    End Class

End Namespace
